# .github/workflows/deploy.yml

name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Ou a branch que você usa como principal

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Replace Supabase Credentials 🔑
        run: |
          # Usa o comando 'sed' para encontrar e substituir os placeholders no script.js
          sed -i "s|__SUPABASE_URL__|${{ secrets.SUPABASE_URL }}|g" script.js
          sed -i "s|__SUPABASE_ANON_KEY__|${{ secrets.SUPABASE_ANON_KEY }}|g" script.js
        
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # A branch que o GitHub Pages usará para publicar
          folder: . # O diretório que contém os arquivos a serem publicados
