# .github/workflows/deploy.yml

name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    # ADICIONE ESTA SEÇÃO DE PERMISSÕES
    permissions:
      contents: write

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Debug and Check Setup 🕵️
        run: |
          echo "Aplicação movida para estrutura ES Module nativa."
          echo "Iniciando build de frontend estático..."
        
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: .
